### ISSUE TITLE
Reika Syntax and Semantics

### ISSUE THREAD

**Issue by at15** [xephonhq/tsdb-proxy-java#1]
Description

This issue keeps track of all the isues related to the general programming language feature part of Reika (the name for the tsdb-ql used in tsdb-proxy-java), SQL part is tracked in #10

Depends on 

- [ ] Type and Symbol checking #4 
  - almost finished, can't move on if function is not added
- [x] Double data type support #7 by @ChujiaoHou 
- [x] Bool data type support #8 by @ChujiaoHou 
- [ ] Date type support #9

Background

This issue is used for discussing the syntax and semantics of the query language, which should be in https://github.com/xephonhq/tsdb-ql but since the Golang version won't work without patching ANTLR runtime https://github.com/xephonhq/tsdb-ql/issues/4 the Java version now have higher priority.

TODO

- [x] general language syntax, variable, function, etc.
  - 63b7fde7a2006c99379ff91bb928e151028a8fda
- [x] ~~sql part syntax~~

Not included 

- [ ] QL for generating fake data, influxdb has provided an good example 
  - https://github.com/influxdata/influxdb/tree/master/stress/v2

````
GO INSERT devices
devices,
city=[str rand(8) 10],country=[str rand(8) 25],device_id=[str rand(10) 1000]
lat=[float rand(90) 0],lng=[float rand(120) 0],temp=[float rand(40) 0]
10000000 10s
````
